### ISSUE TITLE
Demo not working (grey boxes)

### ISSUE THREAD

**Issue by ViktorDB** [flimshaw/Valiant360#14]
When I downloaded the demo from your website it showed me 2 grey boxes. The video is not playing. What did I do wrong? I'm using Chrome.

**Comment by ajmendez** [comment]
Using Inspect Element (right click > inspect element > console) you can see if there is a cross-site error.  I found that the demo would not run without serving it from some host rather than directly from a file.  You can setup a debug server using python: ( python -m SimpleHTTPServer)  from the downloaded directory and then go to localhost:8000 to see if that works.
